name: Workflow Princiapl
on: [push]
jobs:
  build:
    name: Run k6 test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run k6 local test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: poc-test.js
          flags: --vus 10 --duration 3s